### ISSUE TITLE
Photo upload fail

### ISSUE THREAD

**Issue by harshchinu** [commons-app/apps-android-commons#3247]
**Summary:** 

Summarize your issue in one sentence (what goes wrong, what did you expect to happen)

_Before creating an issue, please search the existing issues to see if a similar one has already been created. You can search issues by specific labels (e.g. `label:nearby`) or just by typing keywords into the search filter._

**Steps to reproduce:** 

After downloading the Commons app, I tried to log in to it. it went sucessful now i am trying to upload picture flower taken by me select category and all but after click on submit/upload it isn't uploading it continously tell it failed to upload the images 

**System logs:**

```
Add logcat files here (if possible).

Need help? See https://github.com/commons-app/apps-android-commons/wiki/Getting-app-logs-from-Android-Studio
```

**Device and Android version:** 

What make and model device (e.g., Samsung J7) did you encounter this on?
What Android version (e.g., Android 4.0 Ice Cream Sandwich or Android 6.0 Marshmallow) are you running?
Is it the stock version from the manufacturer or a custom ROM ?
 
**Commons app version:** 

API level: 28
Android version: 9
Device manufacturer: HMD Global
Device model: Nokia 8 Sirocco
Device: A1N_sprout
Network type: cellular-4g
App version name: 2.11.0~93b948d20
User name: harshchinu
Commons app version:

2.11.0

**Screen-shots:** 

https://photos.app.goo.gl/9XdxCEAv5YgM3FSZ9

**Would you like to work on the issue?**

No

**Comment by misaochan** [comment]
Hi @harshchinu  I've just released v2.12 to beta testing, which should contain the fix - it should be available in a few hours. Please let us know if it doesn't work for you. :)

**Comment by harshchinu** [comment]
No, just updated the app and tried again it is failing same issue

**Comment by misaochan** [comment]
Could you check the About page of the app, please, and confirm that you are running v2.12.0?

**Comment by harshchinu** [comment]
Yes

**Comment by neslihanturan** [comment]
Thanks a lot for reporting this issue @harshchinu !
Can you please make sure your username is not banned from editing Wikimedia Commons? Are you able to upload images with web interface? If everything is fine with web interface but you still can't use the app, can you try logging out and in again?

**Comment by harshchinu** [comment]
I am apply upload the image through web portal so i am not in the banned
list obviously
Tried logout and loggin same still not working

**Comment by neslihanturan** [comment]
I would try reinstalling the app to. Would you mind sharing logs with us, it seems like an serious issue?

**Comment by harshchinu** [comment]
Hey i am newbie here so where can i find the log in application

**Comment by neslihanturan** [comment]
Settings-> under feedback title-> send log file

**Comment by harshchinu** [comment]
Thanks

**Comment by ashishkumar468** [comment]
@harshchinu  Are you still facing the issue?

**Comment by harshchinu** [comment]
Let me check and will revert back to you

**Comment by nicolas-raoul** [comment]
Not sure it is the exact same problem, but in the last few weeks (months?) I get upload failures a lot.
When I get on the computer and try reproduce the problem while running adb logcat, the uploads work 🤣
By the way, retry **always** works, I have never seen a retry fail.

**Comment by misaochan** [comment]
@nicolas-raoul Which version of the app are you referring to, is it master (alpha testing)?

**Comment by nicolas-raoul** [comment]
@misaochan Yes, master or very close to it. Actually yesterday I sent a log after such an upload fail, and after the successful retry, using the leaderboard branch which is super close to master.

**Comment by misaochan** [comment]
Pinging @ashishkumar468 to look into this :)

**Comment by ashishkumar468** [comment]
Hi everyone, I looked into the logs sent by @nicolas-raoul. So the this error is thrown when the upload fails
`{"errors":[{"code":"stashfailed","text":"Invalid chunk offset","data":{"offset":"2621440"},"module":"upload"}],"docref":"See https://commons.wikimedia.org/w/api.php for API usage. Subscribe to the mediawiki-api-announce mailing list at &lt;https://lists.wikimedia.org/mailman/listinfo/mediawiki-api-announce&gt; for notice of API deprecations and breaking changes.","servedby":"mw1362"}`

@maskaravivek  Could this be related to your recent commits for the pause/resume feature?

**Comment by maskaravivek** [comment]
Yes, @nicolas-raoul 's issue seems to be related to my changes. There should be a different issue for it as Nicolas is using alpha release and the original issue was for the beta version. I am creating a different issue for this. #3868

We still need to debug @harisankerPradeep's issue.

**Comment by ashishkumar468** [comment]
We don't seem to have logs from @harisankerPradeep. Also, the issue seems to be old (App version 2.11) and there is a high probability that it's already resolved in one of our upload-related bug fixes. Happy to fix this if @harisankerPradeep  can confirm if this is happening with him on one of the latest releases

**Comment by Rishavgupta12345** [comment]
@nicolas-raoul we have a better version of the app now and so we can close this old issue
