### ISSUE TITLE
Release v5.1.0

### ISSUE THREAD

**Issue by sivaraam** [commons-app/apps-android-commons#5715]
The v5.0.1 has been pushed out to beta. Let us use the following milestone to track the issues for which it would be nice to have fixes for:

https://github.com/commons-app/apps-android-commons/milestone/11

The issues kept in the milestone so far are:

- [x] #5758
- [x] #5692
- [x] #5898

Try to converge the following open PR:

- [x] #5771
- [ ] #4902 
- [x] #5761
- [x] #5218 
- [x] #5689 

We could use this issue to discuss further regarding this release 🙂 

PS: For the note, I've also created a milestone for [v5.2.0](https://github.com/commons-app/apps-android-commons/milestone/12) and tagged an issue which would be nice to have in the same.

**Comment by sivaraam** [comment]
Following @mnalis' [suggestion](https://github.com/commons-app/apps-android-commons/issues/5528#issuecomment-2062664504), I just pushed out v5.0.3 with the changes accumulated so far. So, renaming this issue as v5.0.3 for now.

I suppose one major issue that has been reported a bit repeatedly is #5758. So, if we get around finding a fix for it, I suppose we could do a bigfix release.

**Comment by nicolas-raoul** [comment]
Fantastic, great to see such a healthy release pace. :-)

**Comment by nicolas-raoul** [comment]
@sivaraam With GSoC merged and working better than ever, plus Nearby greatly improved, how about releasing a beta? :-)

**Comment by nicolas-raoul** [comment]
@sivaraam I pushed the SDK upgrade deadline to Nov 1, 2024, so we can release without waiting for #5770 if it is before that date. It would be great to do a stable release within that window as there is a possibility that SDK upgrade will take time. Thanks! :-)

**Comment by sivaraam** [comment]
That's nice. I'll look into doing a release soon.

**Comment by DLEI253636863** [comment]
Flag of Loei Province 
https://commons.wikimedia.org/wiki/File%3AFlag_of_Loei_Province.png

**Comment by sivaraam** [comment]
I had a few hiccups with building the project. I've now resovled them. I'll hopefully release a beta version by tbis weekend :-)

**Comment by sivaraam** [comment]
I was just trying to a sanity test of the app using the production variant of the APK to cross check if everything works fine and noticed a weird issue with the upload queue icon flickering and not being visible at all times when there is a pending upload. Was this noticed during the development of the change ?

Here are screen recording to demonstrate the issue: [Queue icon flickering](https://drive.google.com/file/d/15XPLcJ-6nZIF6ISHY3_rJ8E9D84XwO3L/view?usp=drive_link) | [Queue icon only visible after app reopen](https://drive.google.com/file/d/12lD7vPH2Uj2NYMwgbhNo59Oa2MvgKeFJ/view?usp=drive_link)

**Comment by nicolas-raoul** [comment]
I had not seen the first issue in a while, I thought it was solved. Would you mind creating an issue?

The second issue was found 3 weeks ago and is being worked on actively: https://github.com/commons-app/apps-android-commons/issues/5832

**Comment by sivaraam** [comment]
I've opened an issue here: #5847 

I suppose we could do a beta release with this issue but we need at least a stopgap before the production release as it is basically impossible to manage the uploads when the icon is not visible at all.

> The second issue was found 3 weeks ago and is being worked on actively: https://github.com/commons-app/apps-android-commons/issues/5832

I actually added the second one also as a proof to show that the queue is basically invisible while one upload is in progress. You could see the queue icon reappear after I close an reopen the app near the end of the video. I didn't notice the nearby issue that you pointed out. Good to know it is being actively worked on, though.

**Comment by sivaraam** [comment]
I was trying to test the release APK and it seems to me like #5898 is a bit of a blocker for the release as it seems to result in crashes in main flows (after each upload and while using custom selector). Fortunately, it is good that #5902 partially fixed the issue. It seems there are [some non-complete changes](https://github.com/commons-app/apps-android-commons/pull/5902#issuecomment-2440085900) in it, though. So, let's release a beta once the pending changes are done.

**Comment by nicolas-raoul** [comment]
Yes I agree that the app is not in a great shape now.

**Comment by sivaraam** [comment]
Alternatively, I've pushed out a [separate branch v5.1.0](https://github.com/commons-app/apps-android-commons/tree/v5.1.0) which does not have changes in #5891 and #5902. It seems to be working fine without the crashes mentioned above. @nicolas-raoul could you also verify if that works fine without issues ? 

If so, I'll proceed to release it to the beta track.

**Comment by sivaraam** [comment]
Got it. I hope we could address it separately. I'll proceed with creating the release notes for this release and pushing the app out to the beta track.

**Comment by nicolas-raoul** [comment]
Great! 🙂

**Comment by nicolas-raoul** [comment]
https://github.com/commons-app/apps-android-commons/issues/5910

**Comment by nicolas-raoul** [comment]
https://github.com/commons-app/apps-android-commons/issues/5845#issuecomment-2451096617

**Comment by sivaraam** [comment]
After much delay I just [tagged the v5.1.0](https://github.com/commons-app/apps-android-commons/releases/tag/v5.1.0) for the beta release with the changes in the [v5.1.0 branch](https://github.com/commons-app/apps-android-commons/tree/v5.1.0). I was planning to push it out to beta in Play store as the current troubles blocking it could hopefully be fixed before the production release. 

I got stuck at one point, though. It seems we now [request the `FOREGROUND_SERVICE_DATA_SYNC`](https://github.com/commons-app/apps-android-commons/blob/main/app/src/main/AndroidManifest.xml#L30) permission. Google Play is asking us to fill a declaration for the same. It seems to have been introduced recently [[ref](https://github.com/commons-app/apps-android-commons/commit/3e915f9848e550800908af6751ce0d93258b8335#diff-7fa6aef292187a049f7a4d6060d8df3ba212d838789c78940bd363344b1c38cdR28)]. It is not clear why we had to add the same for the SDK 34 upgrade. Could you possibly clarify the same @rohit9625 ?

**Comment by rohit9625** [comment]
We are using `Foreground Service` [here](https://github.com/commons-app/apps-android-commons/blob/f011abef1d480a2393818be60dd142309bdb5f93/app/src/main/java/fr/free/nrw/commons/upload/worker/UploadWorker.kt#L181) and creating `ForegroundInfo` [here](https://github.com/commons-app/apps-android-commons/blob/f011abef1d480a2393818be60dd142309bdb5f93/app/src/main/java/fr/free/nrw/commons/upload/worker/UploadWorker.kt#L271) to show `Upload Progress`. When targetting **API 34**, we must specify a `Foreground Service Type`. I followed this [documentation](https://developer.android.com/develop/background-work/background-tasks/persistent/how-to/long-running#foreground-service-type) and declared the service [here](https://github.com/commons-app/apps-android-commons/blob/f011abef1d480a2393818be60dd142309bdb5f93/app/src/main/AndroidManifest.xml#L194) in `AndroidManifest` file. Declaring that service requires [FOREGROUND_SERVICE_DATA_SYNC](https://github.com/commons-app/apps-android-commons/blob/f011abef1d480a2393818be60dd142309bdb5f93/app/src/main/AndroidManifest.xml#L30).

**Comment by sivaraam** [comment]
Thank you very much for the details! I will look into doing the needful 🙂

**Comment by sivaraam** [comment]
Just wanted to mention here that the beta of v5.1.0 has been published successfully in Play Store and is available to our testers. 

I've also announced the beta release itself on the mailing list as I thought it would be worthwhile to communicate the removal of the limited connection mode beforehand to the community 
https://lists.wikimedia.org/hyperkitty/list/commons-l@lists.wikimedia.org/thread/TEWHYXXSGQHAXLJKVGIFAKA23JS7GDZD/

**Comment by sivaraam** [comment]
We could focus on the pending issues such as :

- [ ] https://github.com/commons-app/apps-android-commons/issues/5910
- [ ] https://github.com/commons-app/apps-android-commons/issues/5845#issuecomment-2451096617
- [ ] https://github.com/commons-app/apps-android-commons/pull/5901
- [ ] https://github.com/commons-app/apps-android-commons/pull/5914 and other latest changes in main

**Comment by mnalis** [comment]
> Just wanted to mention here that the beta of v5.1.0 has been published successfully in Play Store and is available to our testers.

Glad to see new release! :rocket: 
However, it would've be advisable in the future to mark beta releases with `beta` in the tag name, e.g. like we had for e.g. `v4.2.0-beta`.
As it was tagged with just plain numbers, it has already been picked up and published as **release** version by [F-droid](https://f-droid.org/en/packages/fr.free.nrw.commons/). Hopefully it's not too buggy :cold_sweat:  (note: it is also possible to publish betas on F-droid, so only people who have _"Unstable updates"_ enabled will receive the update automatically).

> I've also announced the beta release itself on the mailing list as I thought it would be worthwhile to communicate the removal of the limited connection mode to the community before the production release on Play Store. ( [ref](https://lists.wikimedia.org/hyperkitty/list/commons-l@lists.wikimedia.org/thread/TEWHYXXSGQHAXLJKVGIFAKA23JS7GDZD/) )

I have yet to test new release, but while I hope that new queue fixes upload issues / data losses (which was by far the biggest problem of the app IMHO, e.g. https://github.com/commons-app/apps-android-commons/issues/5762, https://github.com/commons-app/apps-android-commons/issues/5231, ...), on the first sight loss of limited connection mode sounds problematic too, esp. where one is on metered networks where they'd want to conserve as much bandwidth as possible before they get to free wifi. 

Can one choose to have all uploads of media be paused by default (or paused always when on mobile data) in new regime?
I'll have to test it soon when I get some free time.

**Comment by sivaraam** [comment]
> Glad to see new release! 🚀 

❤️ 

> However, it would've be advisable in the future to mark beta releases with `beta` in the tag name, e.g. like we had for e.g. `v4.2.0-beta`. As it was tagged with just plain numbers, it has already been picked up and published as **release** version by [F-droid](https://f-droid.org/en/packages/fr.free.nrw.commons/).

I agree. This is certainly something that I should've done but missed. Thanks for pointing it out.

> Hopefully it's not too buggy 😰

It certainly is not too buggy. You don't have to worry. We've tried to ensure that the basic functionality like uploads work without issues before the release. There are just some glitches here and there.

> (note: it is also possible to publish betas on F-droid, so only people who have _"Unstable updates"_ enabled will receive the update automatically).

Thanks for this note. Will definitely release this as a beta version compatible with Play Store and F-droid from the next release!

> I have yet to test new release, but while I hope that new queue fixes upload issues / data losses (which was by far the biggest problem of the app IMHO, e.g. #5762, #5231, ...), on the first sight loss of limited connection mode sounds problematic too, esp. where one is on metered networks where they'd want to conserve as much bandwidth as possible before they get to free wifi.
> 
> Can one choose to have all uploads of media be paused by default (or paused always when on mobile data) in new regime? I'll have to test it soon when I get some free time.

This is a good suggestion. Having some control over the the default state of the upload based on different networks would certainly be worthwhile to have, I believe. Could you raise a separate issue regarding the same?

**Comment by neeldoshii** [comment]
Hi @sivaraam can we add this issue in milestone for **v5.1.0** or for **v5.2.0** https://github.com/commons-app/apps-android-commons/issues/5994#issue-2717958246 considering as security patch. WDYT?

**Comment by sivaraam** [comment]
Sure, Nicolas. We could certainly include it. 👍🏼

**Comment by nicolas-raoul** [comment]
The app now feels much more stable than 2 weeks ago somehow, almost no "wait" popups anymore. Good time for another beta I would say. :-)

**Comment by nicolas-raoul** [comment]
I haven't used the beta as I focused on main, but if feedback was good then releasing it is would make sense. 🙂

**Comment by sivaraam** [comment]
Sure, Nicolas. I'll try to get it out to production soon including the fix mentioned by Neel and the fix for upload icon flickering.

Excuse the delay. I've got held up with some personal work.

**Comment by sivaraam** [comment]
Just wanted to update here that I pushed out [v5.1.1](https://github.com/commons-app/apps-android-commons/releases/tag/v5.1.1) with the couple of changes that I mentioned and started a staged production roll out on Google Play 🙂 

I'll look into publishing the other accumulated changes as a new beta soon. Thank you everyone for your continued contributions to the app! It is what helps the app thrive ❤️

**Comment by sivaraam** [comment]
Closing this as v5.1.1 is now fully out into production 🙂
