### ISSUE TITLE
Better (developer) app documentation

### ISSUE THREAD

**Issue by janpio** [commons-app/apps-android-commons#809]
As I just started looking into the Commons app I noticed some basic documentation missing. I went ahead and created a few first drafts on the wiki:

Basic list of App Structure and Functionality:

- https://github.com/commons-app/apps-android-commons/wiki/Screen-Structure
- https://github.com/commons-app/apps-android-commons/wiki/App-Functionality

Using these two links you should be able to get a quick overview what the app can do and where you find the functionality in the app.

Initial list of API hosts and endpoints:

- https://github.com/commons-app/apps-android-commons/wiki/External-APIs

This should help to get an overview of the external services the app uses to do its job.

For now I created all this information just by looking at the app. 

Is it roughly correct? 
Do you like the format? 
Should I continue in this style?
Does anything slightly identical exist already (which should be integrated or is even better)?

Next steps would be to actually look at the code to refine everything, add references to code files and classes. I think an additional article about "Local Storage" would probably be helpful as well.

**Comment by neslihanturan** [comment]
Thanks! This was really needed. I read first two document and they looks okay. There are something that I need to read more carefully in API document, will take time for this. 

This structure looks nice for this level of documentation. However if the next plan is going deep with code, structure can be an issue. First question comes to my mind: are you planning to create a structure of classes according to their packages as in code or according to work flows and actions? 

I am sure other people will be deeply interested with this topic and their advices should be very helpful.

**Comment by janpio** [comment]
As I actually have only *just now* cloned the project and opened it in Android Studio I don't know yet. From the complexity I found in the last 3 minutes, I think really documenting this in the wiki ist not a very good idea. 

Maybe "connect the dots" - meaning just a more general writeup "what happens where" in code or something (similar to https://github.com/commons-app/apps-android-commons/wiki/Code-walkthrough-for-new-devs-(draft)), maybe some references to where the APIs are used, which files belong to which screen, which "services" (non-screen classes) exist and what they do.

**Comment by neslihanturan** [comment]
Actually, there is some mysterious parts in our code. Thus, might be hard to document those parts. On the other hand, we need to do in sooner or later. At least starting from somewhere is nice.

**Comment by janpio** [comment]
I started on this really rudimentary while going through the codebase for the first time:
https://github.com/commons-app/apps-android-commons/wiki/Technical-Overview
I think this level should be enough, maybe a list of files and what is in them.
Everything else should definitely happen inside the source files themselves (which could really use some documentation...).

**Comment by misaochan** [comment]
I really like this! Thanks for making the effort to write all these up, @janpio , I think it will be very helpful to new devs. :)

I would vote for a more general writeup, because our codebase is changing very rapidly. It looks very different today than it was even 6 months ago. So going into more detail might take a lot of effort, for not much payoff.

**Comment by misaochan** [comment]
Thanks again for all the documentation efforts @janpio . We'd like to add your name to the CREDITS.md, if you're okay with that. :) If so, what name would you prefer us to use?

**Comment by janpio** [comment]
"Jan Piotrowski" is fine. Thanks!

**Comment by misaochan** [comment]
Done. :)

**Comment by janpio** [comment]
(Could someone please assign this issue to me as I plan on continue working on it when I have the time)

**Comment by janpio** [comment]
All available documentation is now part of the Wiki. I added an initial structure to the home page that groups it a bit, but someone (or several someones) should go over all the content to see if the order and grouping makes sense.

I am sure some information is duplicated and should be concentrated in one location.
Other information is still missing.

But we have to start somewhere 🐿

**Comment by sivaraam** [comment]
> Actually, there is some mysterious parts in our code.

To comment a little about this statement, that's possibly because the project hasn't **documented the change well**. It would be nice if the project had **guidelines for commit messages** like the one the [git community has](https://github.com/sivaraam/git/blob/master/Documentation/SubmittingPatches#L93). A project that follows a good commit message guideline wouldn't face such complexity issues than a project with good documentation which is bound to become stale as the code changes (just like comments), in my opinion.

So, how about having a commit message guideline?

In case you don't get what I'm trying to say, just see the [commit log for a file](https://github.com/git/git/commits/master/builtin/checkout.c) and you'll get what I'm trying to say.

**Comment by neslihanturan** [comment]
I think it would be really nice, I generally have hard times on creating commit messages. It seems like the guideline of git community is usable for most projects. Do you wish to edit some parts of it to apply it to commons app? 

What do other team members think?

**Comment by sivaraam** [comment]
> Do you wish to edit some parts of it to apply it to commons app?

Sure! I'm not sure what applies to the commons app. Let's discuss that on a PR.

**Comment by janpio** [comment]
I'll close this for now as I think I collected everything that existed in the wiki. Now it is the "task" for everyone to grow and nurture that.
